version: "3.8"

services:
  digipetapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=digipet;User Id=sa;Password=MyPass@word;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
    networks:
      - digipet-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - digipet-network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Developer
      - MSSQL_DATABASE=digipet
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - digipet-network

networks:
  digipet-network:
    driver: bridge

volumes:
  sqlserver_data:
